### ISSUE TITLE
Show reason for dependency conflict

### ISSUE THREAD

**Issue by JustusAdam** [elm-lang/elm-package#119]
## Current situation

If your projects has dependencies with internal version conflicts, like

{( p₂ | 1.0.0 ≤ v < 2.0), ( p₃ | 1.0.0 ≤ v < 2.0)} ⇒ p₁ ⋏ {( p₂ | 2.0.0 ≤ v < 3.0.0)} ⇒ p₃

The error message thrown when trying to install p₁ is just

> Error: Unable to find a set of packages that will work with your constraints.

## The problem

This requires manual dependency tracing to find the offending package(s) which, for even marginally larger projects, can be very laborious.

## Solution?

Since the package manager resolves and tests the constraints anyway why not have him spit out whatever the last and final encountered conflict was? Preferably with a resolution trace attached, sort of like cabal does it.

I imagine something like this:

```
Error: Unable to find a set of packages that will work with your constraints.

tried resolving dependencies for: p₁
tried resolving dependencies for: p₃
encountered conflict with p₂ : 
     p₁ requires version [1.0.0  2.0.0)
     p₃ requires version [2.0.0  3.0.0) 
```

Or similar.

It does not matter whether this is the actual offending package (in the sense of being the one that needs fixing) but it gives you a start of where to look for the conflicts origin.

**Comment by jessitron** [comment]
+1
I hit this too, and the message didn't give me a clear picture of what to do about it.

**Comment by ilkka** [comment]
I hit this too, and thought that perhaps `Solver` could use `Data.Either` instead of `Maybe`. I'm a total Haskell newbie but wanted to give it a shot anyway, so the first thing I did was come up with a `stack.yaml` that seems to work. Here it is for posterity:

```yaml
# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-2.22

# Local packages, usually specified by relative directory name
packages:
- location:
    git: https://github.com/elm-lang/elm-compiler.git
    commit: 7fbdee067b494c0298d07c944629aaa5d3fa82f5
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - blaze-html-0.7.1.0
  - blaze-markup-0.6.3.0
  - blaze-builder-0.3.3.4
  - mtl-2.2.1
  - transformers-0.4.3.0
  - transformers-compat-0.4.0.4

# Override default flag values for local packages and extra-deps
flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
```
